const { app, BrowserWindow, ipcMain, session } = require("electron");
const fs = require("node:fs/promises");
const fsSync = require("node:fs");
const os = require("node:os");
const path = require("node:path");

app.commandLine.appendSwitch("autoplay-policy", "no-user-gesture-required");

const YOUTUBE_PARTITION = "persist:youtube-auth";
const AUTH_COOKIE_NAMES = [
  "SAPISID",
  "__Secure-1PAPISID",
  "__Secure-3PAPISID",
  "SID",
  "__Secure-1PSID",
  "__Secure-3PSID",
  "LOGIN_INFO",
];

function getYoutubeCookiePath() {
  const appData = process.env.APPDATA || path.join(os.homedir(), "AppData", "Roaming");
  return path.join(appData, "MusicType", "youtube-cookies.txt");
}

async function getYoutubeCookies() {
  const authSession = session.fromPartition(YOUTUBE_PARTITION);
  const [musicCookies, youtubeCookies] = await Promise.all([
    authSession.cookies.get({ domain: "music.youtube.com" }),
    authSession.cookies.get({ domain: ".youtube.com" }),
  ]);

  const merged = new Map();
  for (const cookie of [...musicCookies, ...youtubeCookies]) {
    merged.set(`${cookie.domain}|${cookie.path}|${cookie.name}`, cookie);
  }

  return [...merged.values()];
}

function hasAuthCookies(cookies) {
  return cookies.some((cookie) => AUTH_COOKIE_NAMES.includes(cookie.name));
}

function toNetscapeCookieFile(cookies) {
  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by MusicType from the app session.",
    "",
  ];

  for (const cookie of cookies) {
    const includeSubdomains = cookie.domain.startsWith(".") ? "TRUE" : "FALSE";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate).toString() : "0";
    const sameSiteNone = cookie.sameSite === "no_restriction";
    const domain = sameSiteNone && !cookie.domain.startsWith(".") ? `.${cookie.domain}` : cookie.domain;

    lines.push(
      [
        domain,
        includeSubdomains,
        cookie.path || "/",
        secure,
        expires,
        cookie.name,
        cookie.value,
      ].join("\t")
    );
  }

  return `${lines.join("\n")}\n`;
}

async function writeYoutubeCookiesFile(cookies) {
  const cookiePath = getYoutubeCookiePath();
  await fs.mkdir(path.dirname(cookiePath), { recursive: true });
  await fs.writeFile(cookiePath, toNetscapeCookieFile(cookies), "utf8");
  return cookiePath;
}

async function readCookieStatus() {
  const cookiePath = getYoutubeCookiePath();

  try {
    const stats = await fs.stat(cookiePath);
    return {
      exists: true,
      path: cookiePath,
      updatedAt: stats.mtimeMs,
    };
  } catch {
    return {
      exists: false,
      path: cookiePath,
      updatedAt: null,
    };
  }
}

async function exportYoutubeCookiesIfAvailable() {
  const cookies = await getYoutubeCookies();
  if (!hasAuthCookies(cookies)) {
    return null;
  }

  const cookiePath = await writeYoutubeCookiesFile(cookies);
  return {
    status: "ready",
    path: cookiePath,
    cookieCount: cookies.length,
  };
}

async function openYoutubeAuthWindow() {
  const existing = await exportYoutubeCookiesIfAvailable();
  if (existing) {
    return existing;
  }

  const parentWindow = BrowserWindow.getAllWindows()[0];

  return new Promise((resolve) => {
    const authWindow = new BrowserWindow({
      width: 1180,
      height: 820,
      parent: parentWindow,
      modal: false,
      autoHideMenuBar: true,
      title: "Connect YouTube Music",
      webPreferences: {
        partition: YOUTUBE_PARTITION,
        nodeIntegration: false,
        contextIsolation: true,
      },
    });

    let finished = false;

    const finish = (payload) => {
      if (finished) {
        return;
      }

      finished = true;
      clearInterval(pollTimer);

      if (!authWindow.isDestroyed()) {
        authWindow.close();
      }

      resolve(payload);
    };

    const pollTimer = setInterval(async () => {
      try {
        const result = await exportYoutubeCookiesIfAvailable();
        if (result) {
          finish(result);
        }
      } catch (error) {
        finish({
          status: "error",
          message: error instanceof Error ? error.message : "Failed to extract YouTube cookies",
        });
      }
    }, 2000);

    authWindow.on("closed", () => {
      if (!finished) {
        clearInterval(pollTimer);
        resolve({
          status: "cancelled",
          message: "YouTube sign-in window was closed before cookies were captured.",
        });
      }
    });

    authWindow.loadURL("https://music.youtube.com").catch((error) => {
      finish({
        status: "error",
        message: error instanceof Error ? error.message : "Failed to open YouTube Music sign-in window",
      });
    });
  });
}

/* ─── Window & Server ─── */

function createWindow(port) {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    icon: path.join(__dirname, "public", "logo.png"),
    webPreferences: {
      preload: path.join(__dirname, "preload.cjs"),
      nodeIntegration: false,
      contextIsolation: true,
    },
    autoHideMenuBar: true,
    show: false,
  });

  win.loadURL(`http://localhost:${port}`);

  // Only show when content is ready (avoids white flash)
  win.once("ready-to-show", () => {
    win.show();
  });
}

const isDev = process.env.NODE_ENV === "development";

async function runNextAndCreateWindow() {
  if (isDev) {
    createWindow(3000);
    return;
  }

  // ── Production: boot a real Next.js server inside Electron ──

  // Expose the user-data directory for yt-dlp downloads, etc.
  process.env.MUSICTYPE_USER_DATA = app.getPath("userData");

  // Tell Next.js where the app lives
  const appDir = __dirname;

  // Verify the .next build exists
  const dotNextPath = path.join(appDir, ".next");
  if (!fsSync.existsSync(dotNextPath)) {
    console.error("FATAL: .next directory not found at", dotNextPath);
    app.quit();
    return;
  }

  const next = require("next");
  const http = require("http");
  const { parse } = require("url");

  // Pick a random ephemeral port
  const port = 30000 + Math.floor(Math.random() * 10000);

  const nextApp = next({
    dev: false,
    dir: appDir,
    hostname: "localhost",
    port: port,
  });

  const handler = nextApp.getRequestHandler();

  try {
    await nextApp.prepare();
    console.log("[MusicType] Next.js prepared successfully");
  } catch (err) {
    console.error("[MusicType] Failed to prepare Next.js:", err);
    app.quit();
    return;
  }

  const server = http.createServer((req, res) => {
    const parsedUrl = parse(req.url, true);
    handler(req, res, parsedUrl);
  });

  server.listen(port, "127.0.0.1", () => {
    console.log(`[MusicType] Server ready on http://127.0.0.1:${port}`);
    createWindow(port);
  });

  // Ensure the server shuts down cleanly
  app.on("before-quit", () => {
    server.close();
  });
}

app.whenReady().then(() => {
  ipcMain.handle("youtube-cookies-status", async () => {
    return readCookieStatus();
  });

  ipcMain.handle("youtube-cookies-ensure", async () => {
    const ready = await exportYoutubeCookiesIfAvailable();
    if (ready) {
      return ready;
    }

    return openYoutubeAuthWindow();
  });

  runNextAndCreateWindow();

  app.on("activate", function () {
    if (BrowserWindow.getAllWindows().length === 0) runNextAndCreateWindow();
  });
});

app.on("window-all-closed", function () {
  if (process.platform !== "darwin") app.quit();
});
